import {sendQueryPathNamed, wait} from "../lib";
import {appendFile} from "fs/promises";

const imiona = [
    "ALEKSANDER",
    "BARBARA",
    "ADAM",
    "RAFAL",
    "ANDRZEJ",
    "AZAZEL",
    "GABRIEL",
    "GLITCH",
        "ADAM",
        "ADRIAN",
        "AGATA",
        "AGNIESZKA",
        "ALAN",
        "ALBERT",
        "ALEKSANDER",
        "ALEKSANDRA",
        "ALICJA",
        "AMELIA",
        "ANA",
        "ANDRZEJ",
        "ANETA",
        "ANNA",
        "ANTONI",
        "ARKADIUSZ",
        "ARTUR",
        "BARBARA",
        "BARTLOMIEJ",
        "BARTOSZ",
        "BEATA",
        "BOGDAN",
        "BOZENA",
        "CEZARY",
        "DAMIAN",
        "DANIEL",
        "DARIUSZ",
        "DAWID",
        "DOMINIK",
        "DOROTA",
        "ELZ̈BIETA",
        "EMILIA",
        "EWA",
        "EWELINA",
        "FILIP",
        "FRANCISZEK",
        "GRZEGORZ",
        "HALINA",
        "HANNA",
        "HENRYK",
        "IGOR",
        "IRENA",
        "IWONA",
        "JACEK",
        "JAKUB",
        "JAN",
        "JANINA",
        "JANUSZ",
        "JAROSLAW",
        "JERZY",
        "JOANNA",
        "JOLANTA",
        "JOZEF",
        "JULIA",
        "JUSTYNA",
        "KAMIL",
        "KAROL",
        "KAROLINA",
        "KATARZYNA",
        "KAZIMIERZ",
        "KINGA",
        "KRYSTYNA",
        "KRZYSZTOF",
        "LAURA",
        "LENA",
        "LEON",
        "LESZEK",
        "LUCYNA",
        "LUKASZ",
        "MACIEJ",
        "MAGDALENA",
        "MAJA",
        "MALGORZATA",
        "MAREK",
        "MARIA",
        "MARIANNA",
        "MARIUSZ",
        "MARTA",
        "MARCIN",
        "MATEUSZ",
        "MICHAL",
        "MIECZYSLAW",
        "MIKOLAJ",
        "MILOSZ",
        "MIROSLAW",
        "MONIKA",
        "NATALIA",
        "NIKODEM",
        "OLIWIA",
        "PATRYCJA",
        "PATRYK",
        "PAWEL",
        "PIOTR",
        "RAFAL",
        "ROBERT",
        "ROMAN",
        "RYSZARD",
        "SEBASTIAN",
        "SLAWOMIR",
        "STANISLAW",
        "STEFAN",
        "SZYMON",
        "TADEUSZ",
        "TOMASZ",
        "WIESLAW",
        "WIKTOR",
        "WOJCIECH",
        "ZBIGNIEW",
        "ZOFIA",
        "ZUZANNA",


    ]
;

const queryPeople = async (person) => {
    let response = '';
    try {
        response = await sendQueryPathNamed(person, 'people');
    } catch (e) {
        response = e;
    }
    await appendFile('./dane/dump3.log', `${person}: ${response}\n`);
    console.log(person, response);
};


for (const imie of imiona) {
    await queryPeople(imie);
    await wait(1000);
}
